export const ADD_LOADER_BUTTON = 'ADD_LOADER_BUTTON';
export const REMOVE_LOADER_BUTTON = 'REMOVE_LOADER_BUTTON';
export const TOGGLE_THEME_MODE = 'TOGGLE_THEME_MODE';
export const SET_THEME_MODE = 'SET_THEME_MODE';